# Generated by Django 3.2.15 on 2022-10-31 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_is_employee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={'permissions': [('change_user_password', 'Change user password')]},
        ),
    ]
