# Generated by Django 3.2.6 on 2022-05-02 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('path', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=50)),
                ('breadcrumb', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('OPEN', 'Нээлттэй'), ('CLOSED', 'Хаалттай')], max_length=10)),
                ('priority', models.PositiveSmallIntegerField(default=1000)),
                ('submenu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
            ],
            options={
                'permissions': [('view_home', 'View home'), ('configs', 'Configs tab'), ('view_student_report', 'View Student report'), ('view_mark_report', 'View mark report')],
            },
        ),
    ]
