# Generated by Django 3.2.15 on 2023-01-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'permissions': [('view_home', 'View home'), ('configs', 'Configs tab'), ('view_student_report', 'View Student report'), ('view_mark_report', 'View mark report'), ('view_report', 'View report')]},
        ),
    ]
