# Generated by Django 3.2.15 on 2022-10-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0003_subject_part'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='credit',
            field=models.DecimalField(decimal_places=2, max_digits=200),
        ),
    ]
