# Generated by Django 3.2.15 on 2023-01-12 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0005_subject_mark_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='mark_variety',
        ),
    ]
