# Generated by Django 3.2.6 on 2022-05-02 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schoolyear', '__first__'),
        ('subject', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Online_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='static/uploads/default/online_lessons/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Online_lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Нээлттэй'), ('CLOSED', 'Хаалттай')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('schoolyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyear.schoolyear')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subject.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Online_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Online_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Нээлттэй'), ('CLOSED', 'Хаалттай')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('online_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_lesson.online_file')),
                ('online_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_lesson.online_lesson')),
                ('online_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_lesson.online_type')),
            ],
        ),
        migrations.CreateModel(
            name='Online_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_lesson.online_lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Online_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('online_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_lesson.online_sub')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
