# Generated by Django 3.2.15 on 2022-10-12 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_lesson', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='online_sub',
            name='online_file',
        ),
        migrations.CreateModel(
            name='Online_sub_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('online_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_lesson.online_file')),
                ('online_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='online_lesson.online_sub')),
            ],
        ),
        migrations.CreateModel(
            name='Online_file_folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sub_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_lesson.online_file_folder')),
            ],
        ),
        migrations.AddField(
            model_name='online_file',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='online_lesson.online_file_folder'),
        ),
    ]
