# Generated by Django 3.2.6 on 2022-05-02 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '__first__'),
        ('section', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Live_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(blank=True, max_length=765)),
                ('client_secret', models.CharField(blank=True, max_length=765)),
                ('api_key', models.CharField(blank=True, max_length=765)),
                ('api_secret', models.CharField(blank=True, max_length=765)),
                ('data', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('OPEN', 'Нээлттэй'), ('CLOSED', 'Хаалттай')], max_length=10)),
                ('type', models.CharField(choices=[('WEBINAR', 'Вебинар'), ('ZOOM', 'Хурал')], default='WEBINAR', max_length=10)),
                ('meeting_id', models.TextField(blank=True)),
                ('password', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
