# Generated by Django 3.2.15 on 2022-10-06 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='address_live',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='surname',
        ),
    ]
