# Generated by Django 3.2.20 on 2023-10-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20231011_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
