# Generated by Django 3.2.20 on 2023-10-11 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='join_date',
            field=models.DateField(null=True),
        ),
    ]
