# Generated by Django 3.2.15 on 2022-11-17 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='group',
        ),
        migrations.CreateModel(
            name='SupportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('support', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.support')),
            ],
        ),
    ]
