# Generated by Django 3.2.6 on 2022-05-02 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sub_school', '__first__'),
        ('program', '__first__'),
        ('school', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '__first__'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes', models.CharField(max_length=150)),
                ('classes_mgl', models.CharField(max_length=250)),
                ('classes_numeric', models.CharField(max_length=50)),
                ('max_student_num', models.IntegerField()),
                ('status', models.CharField(choices=[('OPEN', 'Суралцаж буй'), ('CLOSED', 'Төгссөн')], max_length=30)),
                ('course', models.IntegerField()),
                ('end_course', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.degree')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('sub_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sub_school.sub_school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
