# Generated by Django 3.2.15 on 2022-09-07 06:15

import apps.employee.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=40, unique=True)),
                ('surname', models.CharField(blank=True, max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('registerNo', models.CharField(max_length=50)),
                ('photo', models.ImageField(default='default.jpg', upload_to=apps.employee.models.user_directory_path)),
                ('phone', models.CharField(blank=True, max_length=8)),
                ('phone2', models.CharField(blank=True, max_length=8)),
                ('address', models.TextField(blank=True)),
                ('address_live', models.TextField(blank=True)),
                ('citizen', models.CharField(max_length=80)),
                ('join_date', models.DateField(blank=True)),
                ('join_before', models.CharField(blank=True, max_length=120)),
                ('sex', models.CharField(max_length=10)),
                ('birthdate', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('birth_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('birth_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.teacher_status')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
