# Generated by Django 3.2.15 on 2022-10-17 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_compartment'),
        ('employee', '0003_auto_20221006_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employee_compartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.employee_compartment'),
        ),
    ]
