# Generated by Django 3.2.15 on 2022-10-21 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_employee_compartment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='employee_compartment',
            new_name='compartment',
        ),
    ]
