# Generated by Django 3.2.6 on 2022-05-02 12:49

import apps.student.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schoolyear', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('section', '0001_initial'),
        ('school', '0001_initial'),
        ('classes', '0001_initial'),
        ('program', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_code', models.CharField(max_length=40, unique=True)),
                ('registerNo', models.CharField(max_length=50)),
                ('religion', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('family_name', models.CharField(max_length=100)),
                ('family_name_mgl', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('name_mgl', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('citizen', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default.jpg', upload_to=apps.student.models.user_directory_path)),
                ('phone', models.CharField(blank=True, max_length=8)),
                ('phone2', models.CharField(blank=True, max_length=8)),
                ('address', models.TextField(blank=True)),
                ('address_live', models.TextField(blank=True)),
                ('join_date', models.CharField(blank=True, max_length=20)),
                ('join_before', models.CharField(blank=True, max_length=100)),
                ('sex', models.CharField(max_length=10)),
                ('birthdate', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('birth_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.city')),
                ('birth_district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.district')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('classtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classtime')),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL)),
                ('degree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.degree')),
                ('join_schoolyear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schoolyear.schoolyear')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student_status')),
                ('status_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student_status_extra')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_date', models.CharField(blank=True, max_length=120)),
                ('doc_num', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('old_data', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.activity')),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.classes')),
                ('classtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classtime')),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='program.program')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='section.section')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student_status')),
                ('status_extra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student_status_extra')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
