# Generated by Django 3.2.15 on 2022-10-06 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address_live',
        ),
    ]
