# Generated by Django 3.2.20 on 2023-10-12 05:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employee_compartment'),
        ('student', '0003_remove_student_address_live'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='student',
            name='family_name_mgl',
        ),
        migrations.RemoveField(
            model_name='student',
            name='name_mgl',
        ),
        migrations.RemoveField(
            model_name='student',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='student',
            name='religion',
        ),
        migrations.RemoveField(
            model_name='student',
            name='state',
        ),
        migrations.RemoveField(
            model_name='student',
            name='surname',
        ),
        migrations.AlterField(
            model_name='student',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.city'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.district'),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='join_date',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
