# Generated by Django 3.2.15 on 2023-01-12 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0002_auto_20230112_1153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark_board',
            name='mark_variety',
        ),
    ]
