# Generated by Django 3.2.15 on 2023-01-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0003_remove_mark_board_mark_variety'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark_setting',
            name='mark_variety',
        ),
        migrations.AddField(
            model_name='mark_setting',
            name='part',
            field=models.CharField(choices=[('A', 'Ерөнхий суурь хэсэг'), ('B', 'Техникийн /Мэргэжлийн/ суурь хэсэг'), ('C', 'Мэргэшүүлэх хэсэг')], default='A', max_length=5),
        ),
    ]
