# Generated by Django 3.2.15 on 2023-01-13 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mark', '0004_auto_20230112_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark_setting',
            name='pass_val',
            field=models.IntegerField(default=60),
        ),
    ]
