# Generated by Django 3.2.6 on 2022-05-02 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diplom_archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='static/uploads/default/diplom/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
        migrations.CreateModel(
            name='Diplom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('main_mid', models.TextField()),
                ('main_bottom1', models.TextField()),
                ('main_bottom2', models.TextField()),
                ('main_bottom3', models.TextField()),
                ('mgl_main_mid', models.TextField()),
                ('mgl_main_bottom1', models.TextField()),
                ('mgl_main_bottom2', models.TextField()),
                ('mgl_main_bottom3', models.TextField()),
                ('mgl_main_bottom1_sub', models.TextField()),
                ('mgl_main_bottom2_sub', models.TextField()),
                ('mgl_main_bottom3_sub', models.TextField()),
                ('mark_bottom1', models.TextField()),
                ('mark_bottom2', models.TextField()),
                ('mgl_mark_bottom1', models.TextField()),
                ('mgl_mark_bottom2', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('create_userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
